apiVersion: zelos.zelosai.io/v1alpha1
kind: ZelosGateway
metadata:
  name: default
  namespace: zelos
spec:
  replicas: 2
  image:
    repository: ghcr.io/zelosai/zelosgateway
    tag: develop
  imagePullSecrets:
    - name: ghcr-pull-secret
  backplaneRef: default
  mcpRef: default
  config:
    ZELOSGATEWAY_LOG_FORMAT: "json"
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 70
