apiVersion: zelos.zelosai.io/v1alpha1
kind: ZelosBroker
metadata:
  name: default
  namespace: zelos
spec:
  replicas: 1
  image:
    repository: ghcr.io/zelosai/zelosbroker
    tag: develop
  imagePullSecrets:
    - name: ghcr-pull-secret
  persistence:
    enabled: true
    size: 5Gi
  tunnelTransport: mtls-ws
  allowedLLMHosts:
    - localhost:8000
