apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Install bundle for the zelosai operator.
# `kubectl apply -k deploy/operator/` installs CRDs, RBAC, and the controller manager into `zelos-system`.

resources:
- ../../config/default

images:
- name: ghcr.io/zelosai/zelosai
  newTag: develop
