apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/zelos.zelosai.io_zelosplatforms.yaml
- bases/zelos.zelosai.io_zelosgateways.yaml
- bases/zelos.zelosai.io_zelosbackplanes.yaml
- bases/zelos.zelosai.io_zelosmcps.yaml
- bases/zelos.zelosai.io_zelosbrokers.yaml
- bases/zelos.zelosai.io_zelosservers.yaml
- bases/zelos.zelosai.io_zelosclients.yaml
